### ISSUE TITLE
ValueError: the greenlet library is required to use this function. No module named 'greenlet'

### ISSUE THREAD

**Issue by RoTorEx** [Sehat1137/litestar-dishka-faststream#2]
Hi there,

I added `greenlet==3.1.1` into your `requirements.txt` because I was getting error when I trying to send a message into the queue:

```
Traceback (most recent call last):
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/dishka/integrations/faststream.py", line 73, in consume_scope
    return await call_next(msg)
           ^^^^^^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/faststream/broker/wrapper/call.py", line 201, in decode_wrapper
    return await func(msg)
           ^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/fast_depends/use.py", line 148, in injected_wrapper
    r = await real_model.asolve(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/fast_depends/core/model.py", line 542, in asolve
    response = await run_async(call, *final_args, **final_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/fast_depends/utils.py", line 48, in run_async
    return await cast(Callable[P, Awaitable[T]], func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/faststream/utils/functions.py", line 53, in to_async_wrapper
    return await call_or_await(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/fast_depends/utils.py", line 48, in run_async
    return await cast(Callable[P, Awaitable[T]], func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/dishka/integrations/base.py", line 154, in autoinjected_func
    return await func(*args, **kwargs, **solved)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/book_club/controllers/amqp.py", line 19, in handle
    uuid = await interactor(dto)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/book_club/application/interactors.py", line 37, in __call__
    await self._book_gateway.save(book)
  File ".../litestar-dishka-faststream/book_club/infrastructure/gateways.py", line 33, in save
    await self._session.execute(
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in execute
    result = await greenlet_spawn(
                   ^^^^^^^^^^^^^^^
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 64, in greenlet_spawn
    _not_implemented()
  File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 44, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function. No module named 'greenlet'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/faststream/broker/subscriber/usecase.py", line 338, in consume
  |     await h.call(
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/faststream/broker/subscriber/call_item.py", line 172, in call
  |     raise e
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/faststream/broker/subscriber/call_item.py", line 164, in call
  |     result = await call(message)
  |              ^^^^^^^^^^^^^^^^^^^
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/faststream/broker/middlewares/base.py", line 73, in consume_scope
  |     await self.after_consume(err)
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/faststream/broker/middlewares/base.py", line 54, in after_consume
  |     raise err
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/faststream/broker/middlewares/base.py", line 64, in consume_scope
  |     result = await call_next(await self.on_consume(msg))
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/dishka/integrations/faststream.py", line 65, in consume_scope
  |     async with self.container(
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/dishka/async_container.py", line 170, in __aexit__
  |     await self.container.close(exception=exc_val)
  |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/dishka/async_container.py", line 159, in close
  |     raise ExitError("Cleanup context errors", errors)
  | dishka.exceptions.ExitError: Cleanup context errors (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/dishka/async_container.py", line 143, in close
    |     await exit_generator.callable.asend(exception)
    |   File ".../litestar-dishka-faststream/book_club/ioc.py", line 33, in get_session
    |     async with session_maker() as session:
    |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 1071, in __aexit__
    |     await asyncio.shield(task)
    |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 1016, in close
    |     await greenlet_spawn(self.sync_session.close)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 64, in greenlet_spawn
    |     _not_implemented()
    |   File ".../litestar-dishka-faststream/venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 44, in _not_implemented
    |     raise ValueError(
    | ValueError: the greenlet library is required to use this function. No module named 'greenlet'
    +------------------------------------
```

**Comment by Sehat1137** [comment]
@RoTorEx Hi, it's might been connected with this [issue](https://github.com/sqlalchemy/sqlalchemy/issues/7714).

Do you have this problem on Apple M1/Apple M2?

**Comment by RoTorEx** [comment]
Hm... Yeap, it could be. I tried to launch on MacOS 14.5 with Apple M3 pro processor. Should we close this issue in that case?

**Comment by Sehat1137** [comment]
Yes, thanks for letting me know.
I`m going to make a note about this to readme
